name: GotCraftWeb
version: '1.0-SNAPSHOT'
main: me.lubomirstankov.gotCraftWeb.GotCraftWeb
api-version: '1.21'
author: lubomirstankov
description: Redis-based web payment notification system for Minecraft servers

commands:
  gotcraftweb:
    description: Main command for GotCraftWeb plugin
    usage: /<command> [reload|debug|status|help]
    aliases: [gcw]
    permission: gotcraftweb.use

permissions:
  gotcraftweb.use:
    description: Allows using the /gotcraftweb command
    default: op
  gotcraftweb.reload:
    description: Allows reloading the plugin configuration
    default: op
  gotcraftweb.debug:
    description: Allows viewing debug information
    default: op
  gotcraftweb.status:
    description: Allows viewing connection status
    default: op
  gotcraftweb.*:
    description: Grants all GotCraftWeb permissions
    default: op
    children:
      gotcraftweb.use: true
      gotcraftweb.reload: true
      gotcraftweb.debug: true
      gotcraftweb.status: true
